//用户表
CREATE TABLE CIRCLE(
circle_id INT NOT NULL AUTO_INCREMENT,
clrcle_name VARCHAR(30) NOT NULL UNIQUE,
clrcle_level VARCHAR(20),
clrcle_score INT NOT NULL,
create_date DATE NOT NULL,
PRIMARY KEY ( circle_id )) ENGINE=InnoDB DEFAULT CHARSET=utf8;
//用户关系表
CREATE TABLE USER_CIRCLE(
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
circle_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE,
FOREIGN KEY (circle_id) REFERENCES CIRCLE(circle_id) ON DELETE CASCADE,
user_authorization TINYINT(1) NOT NULL,
UNIQUE (user_id, circle_id),
PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
