CREATE TABLE USER(user_id INT NOT NULL AUTO_INCREMENT,nickname VARCHAR(30) NOT NULL UNIQUE,avatar VARCHAR(100),register_date DATE NOT NULL,PRIMARY KEY ( user_id )) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE USER_AUTHS(id INT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL UNIQUE,FOREIGN KEY (user_id) REFERENCES USER(user_id),identity_type VARCHAR(20) NOT NULL,identifier VARCHAR(50) NOT NULL UNIQUE,password VARCHAR(30),is_third tinyint(1) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SELECT (SELECT user_id FROM USER WHERE username = ?)
